In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [14]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target

print(iris_x[:5])
print("-----------------------")
print(iris_y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
-----------------------
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_x, iris_y, random_state = 42, test_size = 50)

   ## KNN with scikit-learn

In [4]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 15, p = 2).fit(x_train, y_train)
y_pred = knn.predict(x_test)

compare_list = np.equal(y_pred, y_test)
accuracy = np.sum(compare_list) * 1./len(y_test)
accuracy

1.0

## KNN

In [15]:
class KNeighborsClassifier():
    def __init__(self, n_neighbors, p):
        self.n_neighbors = n_neighbors # number of neighbors of each instance
        self.p = p # L-p norm
        
    def compute_similarity(self, instance, data):
        return np.sqrt(np.sum((instance - data)**2))
    
    def select_neighbors_for(self, instance):
        neighbors, tmp = [], None
        similarities = []
        for i in range(len(x_train)):
            similarity = self.compute_similarity(instance, x_train[i])
            similarities.append((y_train[i], similarity))
        for i in range(len(similarities)):
            for j in range(i, len(similarities)):
                if similarities[i][1] > similarities[j][1]:
                    tmp = similarities[i]
                    similarities[i] = similarities[j]
                    similarities[j] = tmp
        for i in range(self.n_neighbors):
            neighbors.append(similarities[i][0])
        return neighbors
    
    def assign_label_for(self, instance):
        neighbors = self.select_neighbors_for(instance)
        labels = list(set(neighbors))
        max_label, ans_label = 0, 0
        for label in labels:
            count_label = neighbors.count(label)
            if count_label > max_label:
                max_label = count_label
                ans_label = label
        return ans_label
    
    def predict(self, data_test):
        y_pred = []
        for instance in data_test:
            label = self.assign_label_for(instance)
            y_pred.append(label)
        return y_pred

In [21]:
knn = KNeighborsClassifier(n_neighbors = 15, p = 2)
y_predict = knn.predict(x_test)
compare = np.equal(y_predict, y_test)
np.sum(compare)* 1./len(y_test)

1.0