In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

# Import Data

In [2]:
my_data = pd.read_csv("drug200.csv")
my_data

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [3]:
for item in my_data.columns:
    missing_values = my_data[item].isnull().sum()
    missing_data = missing_values/len(item) * 100
    print("There are {}% missing values in column {}".format(missing_data, item))

There are 0.0% missing values in column Age
There are 0.0% missing values in column Sex
There are 0.0% missing values in column BP
There are 0.0% missing values in column Cholesterol
There are 0.0% missing values in column Na_to_K
There are 0.0% missing values in column Drug


In [10]:
x = my_data.iloc[:, :-1].values
y = my_data.iloc[:, -1].values

array([['F', 'HIGH', 'HIGH'],
       ['M', 'LOW', 'HIGH'],
       ['M', 'LOW', 'HIGH'],
       ['F', 'NORMAL', 'HIGH'],
       ['F', 'LOW', 'HIGH'],
       ['F', 'NORMAL', 'HIGH'],
       ['F', 'NORMAL', 'HIGH'],
       ['M', 'LOW', 'HIGH'],
       ['M', 'NORMAL', 'HIGH'],
       ['M', 'LOW', 'NORMAL'],
       ['F', 'LOW', 'HIGH'],
       ['F', 'HIGH', 'NORMAL'],
       ['M', 'LOW', 'HIGH'],
       ['F', 'LOW', 'HIGH'],
       ['F', 'NORMAL', 'HIGH'],
       ['F', 'HIGH', 'NORMAL'],
       ['M', 'LOW', 'NORMAL'],
       ['M', 'HIGH', 'HIGH'],
       ['M', 'LOW', 'HIGH'],
       ['F', 'HIGH', 'NORMAL'],
       ['M', 'LOW', 'NORMAL'],
       ['M', 'NORMAL', 'HIGH'],
       ['M', 'LOW', 'NORMAL'],
       ['F', 'LOW', 'HIGH'],
       ['F', 'LOW', 'HIGH'],
       ['F', 'HIGH', 'NORMAL'],
       ['M', 'HIGH', 'HIGH'],
       ['F', 'NORMAL', 'NORMAL'],
       ['F', 'LOW', 'NORMAL'],
       ['M', 'LOW', 'HIGH'],
       ['F', 'NORMAL', 'NORMAL'],
       ['M', 'HIGH', 'HIGH'],
       ['M', 'LOW'

# Encode independent variable (X)

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for i in range(1, 4):
    x[:, i] = le.fit_transform(x[:, i])
x

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.942],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.516],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972],
       [23, 1, 1, 0, 7.298],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.917],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.951],
       [18, 0, 2, 1, 8.75],
       [74, 1, 0, 0, 9.567],
       [49, 1, 1, 1, 11.014],
       [65, 0, 0,

# Encode dependent variable (Y)

In [15]:
y = le.fit_transform(y)
y

array([4, 2, 2, 3, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 3, 4, 3, 0, 2, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 3, 3, 0, 3, 3, 3, 4, 1, 4, 3,
       3, 3, 0, 2, 4, 4, 4, 3, 4, 4, 1, 2, 1, 4, 3, 4, 4, 0, 4, 3, 1, 4,
       0, 3, 4, 4, 1, 4, 3, 4, 4, 4, 0, 4, 0, 3, 1, 3, 2, 0, 2, 1, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 0, 0, 2, 3, 4, 3, 3, 4, 1, 4,
       0, 3, 3, 3, 3, 4, 3, 3, 0, 4, 4, 4, 4, 4, 1, 4, 4, 3, 4, 3, 4, 4,
       3, 4, 4, 3, 1, 0, 1, 3, 0, 4, 1, 4, 0, 3, 3, 0, 3, 2, 0, 1, 3, 3,
       4, 2, 0, 4, 2, 3, 3, 1, 3, 4, 4, 4, 4, 3, 4, 0, 3, 3, 4, 4, 0, 4,
       0, 4, 4, 4, 4, 3, 3, 4, 4, 4, 1, 0, 4, 4, 4, 0, 4, 2, 4, 2, 2, 3,
       3, 3], dtype=int64)

# Split the dataset into training set and test set

In [18]:
from sklearn.model_selection import train_test_split

np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
x_test

array([[36, 1, 1, 1, 11.424],
       [16, 0, 0, 1, 15.516],
       [18, 0, 2, 1, 8.75],
       [59, 0, 1, 0, 10.444],
       [47, 1, 1, 1, 33.542],
       [51, 1, 0, 0, 18.295],
       [18, 0, 0, 1, 24.276],
       [28, 0, 2, 0, 12.879],
       [42, 1, 0, 1, 12.766],
       [66, 0, 2, 1, 8.107],
       [29, 1, 0, 0, 12.856],
       [20, 0, 1, 1, 11.686],
       [38, 1, 1, 0, 18.295],
       [19, 0, 0, 0, 13.313],
       [70, 1, 0, 0, 9.849],
       [25, 1, 2, 0, 19.011],
       [65, 1, 0, 1, 11.34],
       [55, 1, 2, 1, 7.261],
       [32, 0, 1, 0, 9.712],
       [54, 1, 2, 0, 24.658],
       [53, 0, 0, 1, 12.495],
       [69, 1, 1, 1, 11.455],
       [61, 0, 1, 1, 7.34],
       [42, 0, 1, 1, 29.271],
       [68, 0, 2, 1, 27.05],
       [38, 0, 1, 1, 29.875],
       [47, 0, 1, 0, 10.067],
       [17, 1, 2, 1, 10.832],
       [19, 0, 0, 1, 25.969],
       [49, 1, 1, 1, 13.598],
       [43, 1, 1, 1, 19.368],
       [23, 1, 1, 0, 7.298],
       [26, 0, 1, 0, 14.16],
       [26, 1, 1, 1, 2